'use client';

import React from 'react';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 w-full min-h-screen">
        {/* Components generated by the builder will be added here */}
      </main>
    </>
  );
}